name: CI

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"

jobs:
  build_and_deploy:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Install draw.io
        run: brew install --cask drawio

      - name: Install Homebrew packages
        run: brew install mdbook 

      - name: Build Docs
        run: ./build-docs.sh

      - name: Deploy to staging
        if: github.event_name == 'pull_request'
        run: npx vercel deploy -t ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy to production
        if: github.event_name == 'push'
        run: npx vercel deploy --prod -t ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
