name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build_and_deploy:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Install draw.io
        run: brew install --cask drawio

      - name: Install Rust toolchain
        run: "curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh  -s -- -y --default-toolchain nightly"

      - name: Install Homebrew packages
        run: brew install mdbook yarn

      - name: Yarn
        run: yarn

      - name: Build Docs
        run: ./build-docs.sh

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
