name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build_and_deploy:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Install draw.io
        run: brew install --cask drawio

      - name: Install Homebrew packages
        run: brew install mdbook yarn

      - name: Build Docs
        run: ./build-docs.sh

      - name: Remove unnecessary files
        run: ./build-docs.sh

      - uses: amondnet/vercel-action@v20
        run: vercel deploy --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
